feat: 메모리 위젯 UI 수정
sunghun7511/gotop pull request #7
Opened 2021-07-20 08:40 UTC by sunghun7511

## 무엇이 변경되었나요?

* 메모리 위젯 UI를 변경하였습니다.

<img width="1242" alt="스크린샷 2021-07-20 오후 5 40 22" src="https://user-images.githubusercontent.com/12845407/126289925-64b5cf6c-da9b-480c-a2fe-dca6f5da1e51.png">

2021-07-20 09:45 UTC, zych1751 requested changes

2021-07-20 09:45 UTC, zych1751 commented on widgets/memory.go
> +	widget.widget.Data = widget.history
제가 interface를 만들때 Update는 데이터 갱신, GetUI는 데이터에 해당하는 View를 리턴하는 것으로 생각했습니다. 지금 그 2개가 바뀐것 같아요!

2021-07-21 02:29 UTC, sunghun7511 commented on widgets/memory.go
> +	widget.widget.Data = widget.history
헐 그러네요!! 고칠게요

2021-07-21 03:10 UTC, calofmijuck approved these changes
수고하셨습니다!

2021-07-24 10:17 UTC, zych1751 approved these changes

2021-07-26 01:52 UTC, merged