fix: CPU 위젯 리팩토링 및 초기화 이슈 수정
sunghun7511/gotop pull request #8
Opened 2021-07-20 16:14 UTC by calofmijuck

## 수정 내역

- 처음에 위젯이 초기화 될 때 모두 값을 0으로 초기화합니다. 이렇게 되면 제일 처음에 계산되는 CPU usage 는 잘못된 값입니다. 따라서 초기화 시 `/proc/stat` 에서 한 번 데이터를 읽어오도록 수정했습니다.
- 기타 리팩토링

2021-07-21 03:00 UTC, sunghun7511 requested changes
에러 처리만 해주세요!

2021-07-21 03:00 UTC, sunghun7511 commented on widgets/cpu.go
> +	userProcessTime, _ := strconv.ParseUint(cpuTimes[0], 10, 64)
err 처리
https://www.youtube.com/watch?v=G6GczDUM270

2021-07-21 03:00 UTC, sunghun7511 commented on widgets/cpu.go
> +	userProcessTime, _ := strconv.ParseUint(cpuTimes[0], 10, 64)
121라인도 ㅎㅎ

2021-07-24 12:30 UTC, zych1751 commented on widgets/cpu.go
> +		log.Fatal(err)
error 처리를 그냥 로그만 찍고 리턴을 하지 않는다면, 실제로 에러가 발생했을때 아래 로직을 실행하다가 `userProcessTime`을 사용할 때 생각지 못한 값이 될 것 같아요.
이전과 같은 `userProcessTime`, `totalTime`을 리턴한다던가 다른 방식으로 에러처리가 필요해 보여요!

2021-07-25 02:40 UTC, calofmijuck commented
@zych1751 일단 에러 처리는 했는데, `/proc/stat` 파일 파싱 도중 에러가 발생하면 그냥 UI를 업데이트 하지 않는 쪽으로 했습니다.
사실 가장 처음 떠오른 방법은 말씀하신 대로 이전과 같은 `userProcessTime`, `totalTime` 을 리턴해주는 것이긴 한데, 이렇게 하게 되면 순간적으로 CPU utilization 이 0% 가 되기 때문에 그냥 UI 갱신에 실패한 것으로 처리하는 것으로 결정했습니다.

그리고 41번째 줄의 `err` 의 경우 초기화에 실패한 것이라고 보고 `system.exit` 같은걸 해줄지 고민이 됩니다. 일단은 전부 `CpuCoreStats` 는 전부 0으로 초기화 해둔 상태입니다.

2021-07-25 02:48 UTC, zych1751 requested changes
처음에 저도 잘못 생각해서 하나 리뷰를 못드렸네요.
`log.Fatal`은 로그를 찍고 프로그램을 종료해요. 종료하는게 의도가 아닌 부분에서는 `log.Print`를 쓰면 좋을 것 같아요.
말씀주신 초기화 중에 에러가 난 경우에는 굳이 0으로 된 값을 리턴하기 보다는 이때 `log.Fatal`로 그냥 로그를 찍고 종료하는게 좋아보여요!

2021-07-25 09:51 UTC, zych1751 approved these changes
:+1:

2021-07-26 02:01 UTC, sunghun7511 commented on widgets/cpu.go
> +func (widget *CpuWidget) pushCoreUsageData(core int, coreUsage float64) {
이거 한 번밖에 호출 안하는 것 같던데 따로 함수로 안빼도 되지 않을까요!

2021-07-26 02:01 UTC, sunghun7511 approved these changes

2021-07-26 02:01 UTC, sunghun7511 commented on widgets/cpu.go
> +func (widget *CpuWidget) pushCoreUsageData(core int, coreUsage float64) {
근데 큰 문제는 없을 것 같아요!

2021-07-26 03:58 UTC, merged